### ISSUE TITLE
KeyError: 'semanticSegments' - Google Maps Timeline has changed their json ouput? 

### ISSUE THREAD

**Issue by devsoft-co-za** [CalculatedCausality/Google-Maps-Timeline-Parser#1]
This project looks great, just what I need. However, after downloading the location history archive from google maps I get the following directory. I tried your script on several of the json files with error KeyError: 'semanticSegments'

├── Location History (Timeline)
│   ├── Records.json
│   ├── Semantic Location History
│   │   ├── 2017
│   │   │   └── 2017_NOVEMBER.json
│   │   ├── 2018
│   │   │   ├── 2018_DECEMBER.json
│   │   │   ├── 2018_FEBRUARY.json
│   │   │   ├── 2018_JANUARY.json
│   │   │   ├── 2018_JULY.json
│   │   │   ├── 2018_JUNE.json
│   │   │   ├── 2018_MARCH.json
│   │   │   ├── 2018_MAY.json
│   │   │   ├── 2018_NOVEMBER.json
│   │   │   ├── 2018_OCTOBER.json
│   │   │   └── 2018_SEPTEMBER.json
│   │   ├── 2019
│   │   │   ├── 2019_APRIL.json
│   │   │   ├── 2019_AUGUST.json
│   │   │   ├── 2019_DECEMBER.json
│   │   │   ├── 2019_FEBRUARY.json
│   │   │   ├── 2019_JANUARY.json
│   │   │   ├── 2019_JULY.json
│   │   │   ├── 2019_JUNE.json
│   │   │   ├── 2019_MARCH.json
│   │   │   ├── 2019_MAY.json
│   │   │   ├── 2019_NOVEMBER.json
│   │   │   ├── 2019_OCTOBER.json
│   │   │   └── 2019_SEPTEMBER.json
│   │   ├── 2020
│   │   │   ├── 2020_FEBRUARY.json
│   │   │   └── 2020_JANUARY.json
│   │   ├── 2021
│   │   │   └── 2021_DECEMBER.json
│   │   ├── 2022
│   │   │   ├── 2022_APRIL.json
│   │   │   ├── 2022_AUGUST.json
│   │   │   ├── 2022_DECEMBER.json
│   │   │   ├── 2022_FEBRUARY.json
│   │   │   ├── 2022_JANUARY.json
│   │   │   ├── 2022_JULY.json
│   │   │   ├── 2022_JUNE.json
│   │   │   ├── 2022_MARCH.json
│   │   │   ├── 2022_MAY.json
│   │   │   ├── 2022_NOVEMBER.json
│   │   │   ├── 2022_OCTOBER.json
│   │   │   └── 2022_SEPTEMBER.json
│   │   ├── 2023
│   │   │   ├── 2023_APRIL.json
│   │   │   ├── 2023_AUGUST.json
│   │   │   ├── 2023_DECEMBER.json
│   │   │   ├── 2023_FEBRUARY.json
│   │   │   ├── 2023_JANUARY.json
│   │   │   ├── 2023_JULY.json
│   │   │   ├── 2023_JUNE.json
│   │   │   ├── 2023_MARCH.json
│   │   │   ├── 2023_MAY.json
│   │   │   ├── 2023_NOVEMBER.json
│   │   │   ├── 2023_OCTOBER.json
│   │   │   └── 2023_SEPTEMBER.json
│   │   └── 2024
│   │       ├── 2024_APRIL.json
│   │       ├── 2024_AUGUST.json
│   │       ├── 2024_FEBRUARY.json
│   │       ├── 2024_JANUARY.json
│   │       ├── 2024_JULY.json
│   │       ├── 2024_JUNE.json
│   │       ├── 2024_MARCH.json
│   │       ├── 2024_MAY.json
│   │       ├── 2024_NOVEMBER.json
│   │       ├── 2024_OCTOBER.json
│   │       └── 2024_SEPTEMBER.json
│   └── Settings.json
└── Maps
    ├── Added dishes, products, activities
    │   └── Added dishes, products, activities.json
    ├── Commute routes
    │   └── Commute routes.json
    ├── Commute settings
    │   └── Commute settings.json
    ├── Electric vehicle settings
    │   └── Electric vehicle settings.json
    ├── My labeled places
    │   └── Labeled places.json
    ├── Questions and Answers
    │   └── Questions and Answers.json
    ├── Requests for services
    │   └── Requests for services.json
    ├── Vehicle profiles
    │   └── Vehicle profiles.json
    ├── Your local followed places
    │   └── Your local followed places.csv
    └── Your personalization feedback
        └── Your personalization feedback.csv
        
        If there is a way to get the correct json format from Google, please add it to the README instructions.

**Comment by CalculatedCausality** [comment]
From what I understand now, the web version of timeline access is completely shut down and you need to be able to access it via the app. I don't actually think it's possible anymore to be able to export the data from Google takeout due to it being deleted off of their servers.

What I ended up needing to do was on a pixel device  going and locating the options from there and requesting exporting as a json file.

I will aspire to do proper documentation in the next week or so.

**Comment by devsoft-co-za** [comment]
> From what I understand now, the web version of timeline access is completely shut down and you need to be able to access it via the app. I don't actually think it's possible anymore to be able to export the data from Google takeout due to it being deleted off of their servers.
> 
> What I ended up needing to do was on a pixel device going and locating the options from there and requesting exporting as a json file.
> 
> I will aspire to do proper documentation in the next week or so.

It's still working for now but you are right - the takeout is getting deprecated (big surprise, Google removing something useful again) 

If you have a way of getting this on mobile and that is the right format for your app, I will be following and awaiting the update eagerly (will be very helpful in future). 

Thanks so much for sharing by  the way, I got it to work with my takeout - the json has some of the same keys so it wasn't as hard as I thought initially. My last 7 years of location data are now in map format!
